* Updated the tenants-list command to adjust for deployments where the tenants api is not running as a registered service. It will strip /v2 from the request url if it gets a response saying, "No tenant found with id v2" and retry after tripping the trailing /v2 from the url path. * Updated tenants-init to preserve the cache file if the current tenant is specified. * Upated tenants-init to use to the current tenant as the suggestion if none is provided in the environment or as an argument. If the current tenant is not one of the options returned from the call to the tenants api, the agave public tenant is used as the suggestion. If that is not in the list returned from the tenants api, the first option returned is used as the suggestion. * Added error message informing the user when no tenants are returned from the api.

diff --git a/bin/tenants-list b/bin/tenants-list
--- a/bin/tenants-list
+++ b/bin/tenants-list
@@ -65,7 +65,23 @@ main() {
 		success "$result"
 	else
 		errorresponse=$(jsonquery "$response" "message")
-		err "$errorresponse"
+
+		# retry at the base path if this is a legacy, unregistered tenant service
+		if [[ "$errorresponse" =~ "No tenant found with id v2" ]] && [[ "${hosturl%/}" =~ (/v2)$ ]] ; then
+      hosturl=${hosturl%/}
+			hosturl=${hosturl%/v2}
+
+			retyresponse=$(main ${args})
+			# if it fails this time, fail the command
+			if (($?)); then
+				err "$retyresponse"
+			# the retry attempt succeeded, so return that
+			else
+				success "$retyresponse"
+			fi
+    else
+			err "$errorresponse"
+		fi
 	fi
 
 
